"""intitial migration

Revision ID: aa7d2696263
Revises: None
Create Date: 2015-08-25 12:20:57.655512

"""

# revision identifiers, used by Alembic.
revision = 'aa7d2696263'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('votes', sa.Integer(), nullable=True))
    op.alter_column('suggestions', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestions', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('suggestions', 'votes')
    ### end Alembic commands ###
